### ISSUE TITLE
Write to Travis API

### ISSUE THREAD

**Issue by andrewgross** [menegazzo/travispy#17]
Hey,

I was looking through this library to see if it had a way to enable Travis CI hooks for a given repository, however it looks like it is just a read-only API wrapper for now. Are there any plans to add write capabilities in the future?

**Comment by menegazzo** [comment]
@andrewgross I'm expanding ``travispy`` on demand. The Travis API only provides the option to enable/disable hooks as you can check [here](http://docs.travis-ci.com/api/#hooks) (unless there is a hidden/undocumented options). I also looked into [travis.rb](https://github.com/travis-ci/travis.rb) repository for any hints on this matter but I found nothing relevant.

Is this enable/disable feature what you want?

**Comment by andrewgross** [comment]
Looks like the flow I need is to run a `SYNC` for a user, then check the hooks, then enable the hook for my new repo.  For now I am just going to do it manually, but here are the docs I am using.

[Sync Repos](http://docs.travis-ci.com/api/?http#users)
![](https://s3.amazonaws.com/captured-pics/jsi2cETJRdyKmJ7asqXzlW4pa5Jv9PWF78.png)

[Hooks](http://docs.travis-ci.com/api/?http#hooks)
![](https://s3.amazonaws.com/captured-pics/7qYX1oAl6liaKvdrC2FcEaf73d347ztzsR.png)

**Comment by menegazzo** [comment]
@andrewgross I was studying this issue and found [this](https://github.com/travis-ci/travis.rb/blob/3b874216575bd6a8088a029d81d81e5be616350f/lib/travis/client/repository.rb#L140): apparently ``hook`` is an "alias" for repository. I will unpublish the ``hook`` call from API incorporating the same solution applied at Ruby library.

**Comment by rdhyee** [comment]
I'm definitely interested in having the equivalent to the following commands in the travis cli:

```
disable: disables a project
enable: enables a project
sync: triggers a new sync with GitHub
```

I'd appreciate any hints on how to add that functionality in my own fork, which if I get working, will send back to you as a pull request.

**Comment by menegazzo** [comment]
@rdhyee 

For ``sync``:

- Create ``sync`` function at ``User`` entity
- Create ``sync`` at API, which will retrieve the current user and then invoke its own ``sync``

For enable/disable:

- Create ``set_hook``, ``enable`` and ``disable`` at ``Repo`` entity following the [same idea](https://github.com/travis-ci/travis.rb/blob/3b874216575bd6a8088a029d81d81e5be616350f/lib/travis/client/repository.rb#L140) applied in Ruby
- Create ``enable`` and ``disable`` at API. It must receive the repo slug or id.

**Comment by Omarasifshaikh** [comment]
+1
