### ISSUE TITLE
Log Body Empty

### ISSUE THREAD

**Issue by JoshTheGoldfish** [menegazzo/travispy#18]
Help Wanted - 

I'm using the following code: 
```python
import travispy

travis = travispy.travispy.TravisPy()
# https://travis-ci.org/servo/servo/builds/74856035
build_id = 74856035
log = travis.build(build_id).jobs[0].log.body

if log == "":
    print "Empty log"
```

This code prints "Empty log" but if you follow the url in the comment, there is a log there. Is this expected?

Thank you.

**Comment by JoshTheGoldfish** [comment]
I checked this out in [Hurl.it](hurl.it) and got the same results. It's probably just a misunderstanding of the travis-ci API on my part.

**Comment by JoshTheGoldfish** [comment]
@menegazzo, I spoke w/ someone at Travis-CI. The reason I was receiving an empty log was because they changed their API for logs. The following request works, given a job_id:

`curl -H "Accept: text/plain; version=2" https://api.travis-ci.org/jobs/55701828/log -v`

**Comment by menegazzo** [comment]
Ok. I will get into this as soon as possible. Tks for reporting.

**Comment by JoshTheGoldfish** [comment]
If you can point me to the applicable code, I don't mind making the changes and submitting a PR. I can get to it next week if that works.

**Comment by menegazzo** [comment]
Sounds good! I really don't know where to start but I'm available on Hangouts and Skype to help you, if you want.

Also, I have a question: did you tried retrieving your log using one of the following lines?

    travis.log(log_id)
    travis.job(job_id).log

**Comment by JoshTheGoldfish** [comment]
I can't say for certain, I never wound up committing any code of that code, and I can't remember which one I used. Historically, I've been getting the build, and then the job_id from the build, so II think `travis.job(job_id).log` was what I was using.

**Comment by jayvdb** [comment]
I initially used the Log object, and it worked on the latest build, but then a few hours later it stopped working.  After much frantic scratching of heads, I found this was the problem, and a simple `requests` get worked around this bug.  My changes for the workaround are very messy (detecting the empty `body` and doing a plain old `requests.get` without caching), and not likely to be suitable for merging.  I'm happy to rewrite them if you havent been working on this.  If so, where do you want the caching to be done - it doesnt seem to fit in the existing caching layer?  I'd be inclined to leave caching to `requests` if possible.

**Comment by JoshTheGoldfish** [comment]
@jayvdb, I haven't been able to put any time into this, so if @menegazzo is cool with it, feel free to take it.

**Comment by menegazzo** [comment]
@jayvdb and @JoshTheGoldfish no problem at all! Feel free to code it!
If you want contact me through e-mail, hangouts, skype, whatever :)
Maybe I will have some spare time next few days so probably I will save some time for TravisPy.

**Comment by jayvdb** [comment]
Well, I've made a little progress, sending through three test framework related PRs that put my travis builds in the green.  Now to attempt doing some real changes.

**Comment by jayvdb** [comment]
fwiw, I have released a [cmd line log fetch tool](https://github.com/jayvdb/travis_log_fetch), and needed to workaround this issue.
https://github.com/jayvdb/travis_log_fetch/blob/master/travis_log_fetch/_store.py#L166
https://github.com/jayvdb/travis_log_fetch/blob/master/setup.py#L50
