### ISSUE TITLE
Requesting for the build via branch id is returning AttributeError

### ISSUE THREAD

**Issue by kevgatch** [menegazzo/travispy#30]
build = t.build(branch.id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/travispy/travispy.py", line 184, in build
    return Build.find_one(self._session, build_id)
  File "/usr/local/lib/python2.7/dist-packages/travispy/entities/_entity.py", line 102, in find_one
    dependency = entity_class._load(contents[name], session)
  File "/usr/local/lib/python2.7/dist-packages/travispy/entities/_entity.py", line 184, in _load
    setattr(entity, key, value)
AttributeError: 'Commit' object has no attribute 'branch_is_default'

I am using Travis Pro and I was able to get branch.id properly using github authentication token. Any idea why im getting this error?

**Comment by menegazzo** [comment]
@kevgatch I have an idea about this problem. Actually as I don't have a Travis Pro account there are some stuff (such as attributes) that I am not really aware. This type of error is "expected".

The solution is very simple: adding the ``branch_is_default`` attribute to the ``Commit`` model. Of course I can't predicted that will make all things work but this particular error will be solved.

As you have a Pro account, let me ask you: is there a separeted documentation for Pro API?

**Comment by jayvdb** [comment]
This also occurs on non-Pro Travis.

Yes, adding `branch_is_default` attribute to the `Commit` model fixes the problem, however that is less than ideal as it means that `travispy` breaks any time that Travis CI adds an attribute to their API.  non-breaking API changes shouldnt cause API clients to break.
IMO the correct solution is to skip the setattr if the attribute isnt known, and issue a logging information message to indicate that there is a property that isnt known to `travispy`.

Another alternative may be to dynamically expand the list of `__slots__` when an unexpected attribute is encountered. I'm not 100% sure about this one.  Dynamic slots sounds like begging for problems.

**Comment by jayvdb** [comment]
#31 works around the underlying problem, ignoring the unknown attribute.

**Comment by menegazzo** [comment]
@jayvdb That is strange: there is nothing on API about ``branch_is_default``. Anyway, fair enough ignoring undocumented attributes.

**Comment by menegazzo** [comment]
Fixed by #31
