### ISSUE TITLE
Release master to PYPI?

### ISSUE THREAD

**Issue by benjaminws** [menegazzo/travispy#34]
Hi,

I won't pretend to know your release cycle or principals, but I'm curious if you would be willing to cut a version from what is in master, or at least sha 82869b66e97d60e07c478a4928e4469a05763fb6

I'm using this now since it has `User.sync()`, which is a feature I need.

Thanks!

**Comment by menegazzo** [comment]
@benjaminws I'll do it this weekend :wink:

**Comment by benjaminws** [comment]
💃

**Comment by menegazzo** [comment]
Done! Enjoy :wink:
