### ISSUE TITLE
Running specific branch of git repo

### ISSUE THREAD

**Issue by Harshdeep1996** [menegazzo/travispy#37]
Is it possible to run a specific branch of git repo rather than just running master always?

**Comment by menegazzo** [comment]
Yes, it is. First of all check if Travis-CI recognizes your branch (see [TravisPy branches page](https://travis-ci.org/menegazzo/travispy/branches) for example).

Then you can do the following:
```python
from travispy import TravisPy
t = TravisPy.github_auth(<your_github_token>)
branch = t.branch('v0.3.5', 'menegazzo/travispy')
for job in branch.jobs:
    job.restart()
```

For more details please check [TravisPy.branch](https://travispy.readthedocs.io/en/stable/api/#travispy.travispy.TravisPy.branch) and [Branch](https://travispy.readthedocs.io/en/stable/entities/#travispy.entities.Branch) docs.
