### ISSUE TITLE
[Question]: Trigger a build without push

### ISSUE THREAD

**Issue by disa-mhembere** [menegazzo/travispy#42]
Travis-CI API now has this functionality documented [here](https://docs.travis-ci.com/user/triggering-builds). Is this functionality wrapped by travispy? I would prefer not to interact with the restful api so I currently hack it by making a change then pushing, but I would rather not.

**Comment by menegazzo** [comment]
API v3 mentioned on the given link is under development so TravisPy does not support it yet. But I think you can achieve this with the following options.

1. Last build
```python
travis.repo('menegazzo/travispy').last_build.restart()
```

2. Specific build
```python
travis.builds(slug='menegazzo/travispy', number="3")[0].restart()
```

For other examples please check the [TravisPy docs](http://travispy.readthedocs.io/en/stable/getting_started/).

**Comment by disa-mhembere** [comment]
Thanks for the response!

Ah yes -- I knew this was possible, but I forgot to mention that it's for a new repo that is now just being tracked by travis so no build exists as yet meaning there is no build to reference to restart ...

Any suggestions?

**Comment by menegazzo** [comment]
I'm out of ideas. Since Travis triggers builds based on pushes, maybe you can programatically force a push to the repo. Maybe we can start mixing v2 and v3 by adding the feature you mentioned first. What about that?

**Comment by disa-mhembere** [comment]
Ok well the programmatic dummy push to the repo works for now, but I'll look into the v3 feature if it's critical.

Thanks for your input.

**Comment by menegazzo** [comment]
Closing until migration to v3 or the feature becomes really necessary.
